import type { Metadata } from "next";
import "./globals.css";
import { inter } from "./fonts";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Kobodrop Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body
        className={`${inter.className} !scroll-smooth antialiased`}
      >
      <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
